### Tìm kiếm chuyến đi
POST http://localhost:5000/api/schedule/
Content-Type: application/json

{
    "fromLocationId": "1",
    "toLocationId": "19",
    "date": "2025-05-16"
}

### Lấy chi tiết chuyến đi
POST http://localhost:5000/api/schedule/detail
Content-Type: application/json

{
    "id": "1"
}

### Lấy tình trạng ghế
POST http://localhost:5000/api/seat/
Content-Type: application/json

{
    "scheduleId": "1"
}

### Đăng ký
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "Nguyễn Công Tuấn Đẹp Trai",
    "email": "user1@gmail.com",
    "password": "123456",
    "phone": "0377033450"
}

### Đăng nhập
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "123456"
}

### Đặt vé (booking)
POST http://localhost:5000/api/booking/
Content-Type: application/json
Authorization: Bearer <token>

{
    "scheduleId": "1",
    "seats": ["A01", "A02"]
} 